### ISSUE TITLE
The example doesn't work for last version of Iggy

### ISSUE THREAD

**Issue by pikhovkin** [iggy-rs/iggy-python-client#2]

**Comment by darioalessandro** [comment]
Hey @pikhovkin can you please add more details? logs/ways to reproduce it?

**Comment by pikhovkin** [comment]
Just run all the steps in the README for the image `iggyrs/iggy:0.0.45`  image and  the current repository version.

Logs for `producer`
```console
stream error {} InvalidResponse(40)
topic error {} InvalidResponse(40)
Messages will be sent to stream: 1, topic: 1, partition: 1 with interval 500.0 ms.
exception: {} InvalidResponse(40)
Sent 10 message(s).
exception: {} InvalidResponse(40)
Sent 10 message(s).
exception: {} InvalidResponse(40)
Sent 10 message(s).
exception: {} InvalidResponse(40)
Sent 10 message(s).
exception: {} InvalidResponse(40)
Sent 10 message(s).
````
Logs for `consumer`
```console
Messages will be consumed from stream: 1, topic: 1, partition: 1 with interval 500.0 ms.
exception: {} IoError(Custom { kind: UnexpectedEof, error: "early eof" })
```
Same problem with `iggyrs/iggy:0.0.46`  image.

**Comment by spetz** [comment]
@pikhovkin that's most likely due to the missing authentication support, as code `40` means `unauthenticated`.

**Comment by pikhovkin** [comment]
> @pikhovkin that's most likely due to the missing authentication support, as code `40` means `unauthenticated`.

@spetz 
and?
how can i solve the problem?

**Comment by spetz** [comment]
@pikhovkin the obligatory authentication on the server side has been introduced in the version 0.0.20, so the simplest way, would to be use an image with the tag < 0.0.20. Of course, that'd result in having less features and recent bug fixes until the Python client catches up to the latest SDK version. 

@darioalessandro do you see it doable in the near future? It's a few additional commands related to the user auth & management (for TCP/UDP client it's just a matter of providing the valid credentials, only for the HTTP integration it'd require storing the additional JWT).

**Comment by darioalessandro** [comment]
I agree with @spetz

**Comment by spetz** [comment]
The 0.1.0 package has been finally [released](https://pypi.org/project/iggy-py/), and it does support the authentication.

**Comment by hubcio** [comment]
@pikhovkin FYI if you didn't notice ;)
