### ISSUE TITLE
Topic with name: sample-topic for stream with ID: 1 was not found.

### ISSUE THREAD

**Issue by pikhovkin** [iggy-rs/iggy-python-client#20]
I followed the following steps:

1. `docker run --rm -p 8080:8080 -p 3000:3000 -p 8090:8090 iggyrs/iggy:0.2.24`
2. `pip install maturin` 
3. `maturin develop` Installed iggy-py-0.2.3
4.  `python producer.py`

Result
```console
Stream was created.
topic error {} InvalidResponse(2014, 18, "Invalid topic name")
Messages will be sent to stream: sample-stream, topic: sample-topic, partition: 1 with interval 500.0 ms.
exception: {} InvalidResponse(2011, 66, "Topic with name: sample-topic for stream with ID: 1 was not found.")
```

**Comment by FireMasterK** [comment]
Hi, you might need to activate the virtual environment before you run the example.
Here are the steps I used to test this (I've recently updated the client to a newer iggy version):
```
docker run -d --name iggy-server -p 3000:3000 -p 8090:8090 --restart unless-stopped iggyrs/iggy:0.4.21
maturin develop
source .venv/bin/activate
python python_examples/producer.py
python python_examples/consumer.py
```

**Comment by mmodzelewski** [comment]
@pikhovkin I'm closing this issue. If the problem still exists, feel free to reopen.
