### ISSUE TITLE
Implement support for iggy connection strings

### ISSUE THREAD

**Issue by FireMasterK** [iggy-rs/iggy-python-client#22]

**Comment by lsabi** [comment]
I think it should be enough to modify the `new` function of [https://github.com/iggy-rs/iggy-python-client/blob/main/src/client.rs](https://github.com/iggy-rs/iggy-python-client/blob/main/src/client.rs) into

```
 #[new]
#[pyfunction]
    fn new(conn: Option<String>) -> Self {
        // TODO: use asyncio
        let runtime = Builder::new_multi_thread()
            .worker_threads(4) // number of worker threads
            .enable_all() // enables all available Tokio features
            .build()
            .unwrap();
    let client = IggyClientBuilder::new()
        .with_tcp()
        .with_server_address(conn.unwrap_or("127.0.0.1:8090".to_string()))
        .build()?;
        IggyClient {
            inner: client,
            runtime,
        }
    }
```

I haven't tested it and don't want to install everything needed for trying it out. Furthermore, there are no tests, so I'm not sure if my changes affect other parts of the code. If someone has already the set up, it would be a great favour to the community to test it and implement it and documenting it (assuming it works).
