### ISSUE TITLE
ImportError: cannot import name 'PollingStrategy' from 'iggy_py'

### ISSUE THREAD

**Issue by lsabi** [iggy-rs/iggy-python-client#30]
Importing the `PollingStrategy` in version `0.2.5` returns this exception

Code to reproduce:
```
from iggy_py import IggyClient, PollingStrategy
```

**Comment by mmodzelewski** [comment]
Hi @lsabi, the polling strategy was added after 0.2.5 and it's not yet released. I'll push create a new release with it.

**Comment by mmodzelewski** [comment]
@lsabi the polling strategy is now available in v[0.2.6](https://github.com/iggy-rs/iggy-python-client/releases/tag/v0.2.6)
